### PR TITLE
Add mogpr timestep option

### LINKED ISSUE #96: Make the time steps size configurable in the mogpr method
When using the [fusets.mogpr method](https://github.com/Open-EO/FuseTS/blob/e7d82a85e403df29dda88bb6cc33f9c95a6de3c7/src/fusets/mogpr.py#L136), the size of the temporal steps is enforced to 5. This constraint is not explained in the documentation: this gave me erroneous output data when I tried to use the method on data that was composited on 10 days.

Would it be possible to let the user specify the size of temporal steps, or maybe to try to deduce it from the input array coordinates?

Implementing a check that raises an error if temporal coordinates do not match the temporal step size would also help the user to use the function correctly.

@JanssenBrm

### PR DESCRIPTION
**Pull request by mlubej**
Changes:
- added the option for a custom timestep (provided as '5D' or '1M' etc.
- fixed a bug where the provided limited set of variables was not used to limit the data

Closes #96 

(cc. @GriffinBabe I tried this out myself and it works, but it wouldn't hurt if you also give it a try)

### CODE REVIEW

**Comment by GriffinBabe** [comment]
In the mogpr function, there is an issue when leaving "prediction_period" as default (None): the "output_time_dimension" is not getting defined in that case. Other than that, the function seems to work fine, I ran mogpr with different prediction periods.

**Comment by mlubej** [comment]
> In the mogpr function, there is an issue when leaving "prediction_period" as default (None): the "output_time_dimension" is not getting defined in that case. Other than that, the function seems to work fine, I ran mogpr with different prediction periods.

@GriffinBabe Is this based on the code review or did you encounter this during execution? It works for me in both cases.

If you ran into the issue, could you please provide a minimal example where I could test this?

**Comment by mlubej** [comment]
> If you ran into the issue, could you please provide a minimal example where I could test this?

I see now I had unpushed commits...

**Comment by GriffinBabe** [comment]
Yes it works now, for me you can merge :)

**Pull request merged**
